version: "3.9"

services:
  web:
    container_name: django-web
    build: ./project
    restart: always
    ports:
      - "5432:5432" # Port for Postgresql
    expose:
      - 8000
    volumes:
      - ./project:/app # Valume for not restarting docker container while coding
      - static_vol:/app/static

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_vol:/app/static
    depends_on:
      - web

volumes:
  static_vol: