version: "3.9"

services:
  web:
    container_name: django-web
    build: ./project
    restart: always
    ports:
      - "5432:5432" # Port for Postgresql
    expose:
      - 8000 # nginx riderect to this port
    volumes:
      - ./project:/app # Valume for not restarting docker container while coding
      - static_vol:/app/static # Static value
    command: gunicorn -c gunicorn.py project.wsgi

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_vol:/app/static
    depends_on:
      - web

  schedule:
    container_name: schedule
    build: ./project
    restart: always
    volumes:
      - ./project:/app # Valume for not restarting docker container while coding
    command: python manage.py runtasks

volumes:
  static_vol: