# Generated by Django 4.0.5 on 2022-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Заказ №')),
                ('price_dollor', models.FloatField(verbose_name='Стоимость, $')),
                ('price_rubl', models.FloatField(verbose_name='Стоимость, рубль')),
                ('delivery_date', models.DateField(verbose_name='Срок поставки')),
            ],
        ),
    ]
