# Generated by Django 4.0.5 on 2022-06-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_alerted_about_delivery_date',
            field=models.BooleanField(default=False, verbose_name='Оповещено о сроке поставке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(blank=True, verbose_name='Срок поставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_id',
            field=models.IntegerField(blank=True, verbose_name='Заказ №'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_dollor',
            field=models.FloatField(blank=True, verbose_name='Стоимость, $'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rubl',
            field=models.FloatField(blank=True, verbose_name='Стоимость, рубль'),
        ),
    ]
