# Generated by Django 4.0.5 on 2022-06-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_is_alerted_about_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Закази'},
        ),
    ]
